# Generated by Django 3.2.2 on 2021-07-03 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='slotAvailability',
        ),
    ]
