# Generated by Django 3.2.2 on 2021-07-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0002_delete_slotavailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='slotAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avalTime', models.DateTimeField()),
            ],
        ),
    ]
